version: "3.1"

networks:
  proxy-net:
    external:
      name: proxy-net

services:
  stabel-io-web:
    container_name: stabel-io-web
    networks:
      - proxy-net  
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=stabel.io
      - VIRTUAL_PORT=80
#      - LETSENCRYPT_HOST=stabel-io
#      - LETSENCRYPT_EMAIL=mail@viktor-braun.de
